"""
"All Properties" export (Manager): one PDF report and one Excel workbook built from the same rows.

The rows are plain dicts produced by `property_row()` from real database records. Only fields a manager needs to review the
portfolio are exported - names of the owner and tenant, but never anyone's email or phone number, and no financial records.
"""
import io
import json
from datetime import datetime
from typing import Dict, Iterable, List, Optional

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.services.export_common import (
    BLUE, FONT, FONT_BOLD, GRID, LIGHT_BLUE, LIGHT_GRAY, NumberedCanvas, clean_text, pdf_markup, set_text,
)

TITLE = "Property Portfolio Report"


def parse_amenities(raw: Optional[str]) -> List[str]:
    """Amenities are stored either as a JSON list or as 'A,B,C' - both are handled."""
    if not raw or not str(raw).strip():
        return []
    text = str(raw).strip()
    items: List[str] = []
    if text.startswith("["):
        try:
            parsed = json.loads(text)
            items = [str(x) for x in parsed] if isinstance(parsed, list) else []
        except ValueError:
            items = text.strip("[]").replace('"', "").split(",")
    else:
        items = text.split(",")
    seen, out = set(), []
    for item in (clean_text(i) for i in items):
        if item and item.lower() not in seen:
            seen.add(item.lower()); out.append(item)
    return out


def property_row(prop, owner_name: Optional[str], tenant_name: Optional[str], listed_on: Optional[str]) -> Dict:
    return {
        "id": prop.id,
        "name": prop.title,
        "address": prop.address,
        "city": prop.city,
        "state": prop.state,
        "pincode": prop.pincode,
        "type": (prop.property_type or "").replace("_", " ").title(),
        "bedrooms": prop.bedrooms,
        "bathrooms": prop.bathrooms,
        "area_sqft": prop.area_sqft,
        "rent": float(prop.rent_amount) if prop.rent_amount is not None else None,
        "status": "Available" if prop.is_available else "Occupied",
        "owner": owner_name,
        "tenant": tenant_name if not prop.is_available or tenant_name else None,
        "amenities": parse_amenities(prop.amenities),
        "latitude": prop.latitude,
        "longitude": prop.longitude,
        "listed_on": listed_on,
        "description": prop.description,
    }


def _summary(rows: List[Dict]) -> Dict:
    occupied = [r for r in rows if r["status"] == "Occupied"]
    return {
        "total": len(rows),
        "occupied": len(occupied),
        "available": len(rows) - len(occupied),
        "rent_all": sum(r["rent"] or 0 for r in rows),
        "rent_occupied": sum(r["rent"] or 0 for r in occupied),
    }


def _inr(value: Optional[float]) -> str:
    return "—" if value is None else f"{value:,.0f}"


def _num(value, unit: str = "") -> str:
    if value in (None, ""):
        return "—"
    return (f"{value:,.0f}" if float(value).is_integer() else f"{value:,.1f}") + unit


# ── PDF ───────────────────────────────────────────────────────────────────────

def generate_properties_pdf(rows: Iterable[Dict], generated_by: str, generated_at: datetime) -> bytes:
    rows = list(rows)
    summary = _summary(rows)
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=landscape(A4), leftMargin=0.5 * inch, rightMargin=0.5 * inch, topMargin=0.5 * inch, bottomMargin=0.6 * inch,
        title=TITLE, author="PropAI", subject="Property portfolio",
    )
    small = ParagraphStyle("cell", fontName=FONT, fontSize=7.5, leading=9.5)
    small_bold = ParagraphStyle("cellb", parent=small, fontName=FONT_BOLD)
    right = ParagraphStyle("cellr", parent=small, alignment=2)
    head = ParagraphStyle("head", fontName=FONT_BOLD, fontSize=7.5, leading=9.5, textColor=colors.white)
    head_right = ParagraphStyle("headr", parent=head, alignment=2)
    story = [
        Paragraph("PropAI — AI-Driven Financial Analytics", ParagraphStyle("app", fontName=FONT, fontSize=9, textColor=colors.grey)),
        Paragraph(TITLE, ParagraphStyle("title", fontName=FONT_BOLD, fontSize=20, leading=24, spaceAfter=4)),
        HRFlowable(width="100%", thickness=2, color=BLUE, spaceAfter=8),
    ]

    meta = [
        ["Generated", pdf_markup(generated_at.strftime("%d %b %Y, %H:%M")), "Generated by", pdf_markup(generated_by)],
        ["Properties", str(summary["total"]), "Occupied / Available", f"{summary['occupied']} / {summary['available']}"],
        ["Monthly rent (all)", f"Rs. {summary['rent_all']:,.0f}", "Monthly rent (occupied)", f"Rs. {summary['rent_occupied']:,.0f}"],
    ]
    mt = Table([[Paragraph(c, small_bold if i % 2 == 0 else small) for i, c in enumerate(r)] for r in meta], colWidths=[1.3 * inch, 2.6 * inch, 1.6 * inch, 2.6 * inch])
    mt.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), LIGHT_BLUE), ("BOX", (0, 0), (-1, -1), 0.6, BLUE), ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4)]))
    mt.hAlign = "LEFT"
    story += [mt, Spacer(1, 12)]

    if not rows:
        story.append(Paragraph("No properties to report. There are no properties in the system yet.", ParagraphStyle("empty", fontName=FONT, fontSize=11, leading=15, textColor=colors.HexColor("#374151"))))
    else:
        cols = ["ID", "Property", "Address", "Type", "BHK", "Area", "Rent (Rs./mo)", "Status", "Owner", "Tenant"]
        widths = [0.35, 1.55, 2.6, 0.85, 0.5, 0.8, 0.95, 0.75, 1.05, 1.05]
        data = [[Paragraph(c, head_right if c in ("Rent (Rs./mo)",) else head) for c in cols]]
        for r in rows:
            location = ", ".join(x for x in (clean_text(r["address"]), clean_text(r["city"]), clean_text(r["state"])) if x)
            if r["pincode"]:
                location += f" - {clean_text(r['pincode'])}"
            data.append([
                Paragraph(str(r["id"]), small), Paragraph(pdf_markup(r["name"]), small_bold), Paragraph(pdf_markup(location), small),
                Paragraph(pdf_markup(r["type"] or "—"), small), Paragraph(_num(r["bedrooms"]), small), Paragraph(_num(r["area_sqft"], " sqft"), small),
                Paragraph(_inr(r["rent"]), right), Paragraph(pdf_markup(r["status"]), small),
                Paragraph(pdf_markup(r["owner"] or "—"), small), Paragraph(pdf_markup(r["tenant"] or "—"), small),
            ])
        table = Table(data, colWidths=[w * inch for w in widths], repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), BLUE),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GRAY]),
            ("GRID", (0, 0), (-1, -1), 0.4, GRID),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(table)

    class Canvas(NumberedCanvas):
        footer_label = f"PropAI · {TITLE} · generated {generated_at.strftime('%d %b %Y')}"
    doc.build(story, canvasmaker=Canvas)
    return buf.getvalue()


# ── Excel ─────────────────────────────────────────────────────────────────────

COLUMNS = [  # (heading, row key, width, kind)
    ("Property ID", "id", 12, "int"), ("Property Name", "name", 30, "text"), ("Address", "address", 40, "wrap"), ("City", "city", 16, "text"),
    ("State", "state", 16, "text"), ("Pincode", "pincode", 10, "text"), ("Property Type", "type", 14, "text"), ("Bedrooms", "bedrooms", 10, "int"),
    ("Bathrooms", "bathrooms", 10, "int"), ("Area (sq ft)", "area_sqft", 12, "num"), ("Monthly Rent (₹)", "rent", 16, "money"), ("Status", "status", 12, "text"),
    ("Owner", "owner", 20, "text"), ("Tenant", "tenant", 20, "text"), ("Amenities", "amenities", 34, "wrap"), ("Latitude", "latitude", 11, "coord"),
    ("Longitude", "longitude", 11, "coord"), ("Listed On", "listed_on", 12, "text"), ("Description", "description", 50, "wrap"),
]


def generate_properties_excel(rows: Iterable[Dict], generated_by: str, generated_at: datetime) -> bytes:
    rows = list(rows)
    summary = _summary(rows)
    wb = Workbook()
    ws = wb.active
    ws.title = "Properties"
    thin = Side(style="thin", color="D1D5DB")
    header_fill = PatternFill(fill_type="solid", fgColor="2563EB")

    for c, (heading, _, width, _) in enumerate(COLUMNS, 1):
        cell = ws.cell(row=1, column=c)
        set_text(cell, heading)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = Border(left=thin, right=thin, top=thin, bottom=thin)
        ws.column_dimensions[get_column_letter(c)].width = width
    ws.row_dimensions[1].height = 24

    for r, row in enumerate(rows, 2):
        for c, (_, key, _, kind) in enumerate(COLUMNS, 1):
            value = row.get(key)
            cell = ws.cell(row=r, column=c)
            if kind == "text":
                set_text(cell, value)
            elif kind == "wrap":
                set_text(cell, ", ".join(value) if isinstance(value, list) else value)
                cell.alignment = Alignment(wrap_text=True, vertical="top")
            elif value is None:
                cell.value = None
            elif kind == "int":
                cell.value = int(value)
            elif kind == "money":
                cell.value = float(value); cell.number_format = '"₹"#,##0'
            elif kind == "coord":
                cell.value = float(value); cell.number_format = "0.0000"
            else:
                cell.value = float(value); cell.number_format = "#,##0.##"
            cell.border = Border(left=thin, right=thin, top=thin, bottom=thin)
        if r % 2 == 1:
            for c in range(1, len(COLUMNS) + 1):
                ws.cell(row=r, column=c).fill = PatternFill(fill_type="solid", fgColor="F3F4F6")

    ws.freeze_panes = "C2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(COLUMNS))}{max(len(rows) + 1, 1)}"

    sm = wb.create_sheet("Summary")
    for i, (label, value) in enumerate([
        ("Report", TITLE), ("Generated", generated_at.strftime("%d %b %Y, %H:%M")), ("Generated by", generated_by),
        ("Total properties", summary["total"]), ("Occupied", summary["occupied"]), ("Available", summary["available"]),
        ("Monthly rent - all properties (₹)", summary["rent_all"]), ("Monthly rent - occupied properties (₹)", summary["rent_occupied"]),
    ], 1):
        set_text(sm.cell(row=i, column=1), label)
        sm.cell(row=i, column=1).font = Font(bold=True)
        cell = sm.cell(row=i, column=2)
        if isinstance(value, str):
            set_text(cell, value)
        else:
            cell.value = value
            if "₹" in label:
                cell.number_format = '"₹"#,##0'
    if not rows:
        set_text(sm.cell(row=10, column=1), "There are no properties in the system yet, so the Properties sheet contains only its column headings.")
    sm.column_dimensions["A"].width = 42
    sm.column_dimensions["B"].width = 28

    out = io.BytesIO()
    wb.save(out)
    return out.getvalue()
