import { chromium } from 'playwright-core'
import fs from 'node:fs'
import path from 'node:path'
import { execFileSync, spawnSync } from 'node:child_process'

const BASE = 'http://localhost:3000', API = 'http://localhost:8000'
const OUT = path.resolve('shots/auth'); fs.mkdirSync(OUT, { recursive: true })
const src = fs.readFileSync('audit.mjs', 'utf8')
const auditFn = new Function('return ' + src.match(/const auditFn = (\(\) => \{[\s\S]*?\r?\n\})\r?\n\r?\nconst browser/)[1])()
const results = []
const check = (name, ok, detail = '') => { results.push(!!ok); console.log((ok ? 'PASS ' : 'FAIL ') + name + (detail !== '' ? `  [${String(detail).slice(0, 200)}]` : '')) }
const pg = (sql) => execFileSync('docker', ['exec', '-i', 'property_postgres', 'psql', '-U', 'postgres', '-d', 'property_management', '-At'], { encoding: 'utf8', input: sql }).trim()
const rd = (...a) => spawnSync('docker', ['exec', 'property_redis', 'redis-cli', ...a], { encoding: 'utf8' }).stdout.trim()
const otpFor = (email) => {
  const p = spawnSync('docker', ['logs', 'property_backend', '--since', '3m'], { encoding: 'utf8', maxBuffer: 512 * 1024 * 1024 })
  const m = [...(p.stdout + p.stderr).matchAll(new RegExp(`verification code for ${email.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')} is (\\d{6})`, 'g'))]
  return m.length ? m[m.length - 1][1] : null
}
const j = async (url, opts = {}, tok) => { const r = await fetch(API + url, { ...opts, headers: { 'Content-Type': 'application/json', ...(tok ? { Authorization: `Bearer ${tok}` } : {}) } }); return { status: r.status, body: await r.json().catch(() => null), headers: r.headers } }
const PW = 'UiAuth-2026!'
const BASEU = pg('select count(*) from users')
const EM = { owner: 'authui_owner@example.com', pending: 'authui_pending@example.com', thrott: 'authui_thrott@example.com', sess: 'authui_sess@example.com', mgr: 'authui_newmgr@example.com', ten: 'authui_newten@example.com' }
const expiredJwt = (id, role) => spawnSync('docker', ['exec', 'property_backend', 'python', '-c', `from datetime import timedelta; from app.utils.security import create_access_token; print(create_access_token({'sub':'${id}','role':'${role}'}, timedelta(seconds=-60)))`], { encoding: 'utf8' }).stdout.trim()

const browser = await chromium.launch({ executablePath: process.env.BROWSER_PATH || 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe', headless: true })
const sessions = []
async function session({ theme = 'light', viewport = { width: 1440, height: 1000 }, clock = false } = {}) {
  const ctx = await browser.newContext({ viewport, colorScheme: theme })
  await ctx.addInitScript((t) => { if (!sessionStorage.getItem('seeded')) { localStorage.setItem('propai-theme', t); sessionStorage.setItem('seeded', '1') } }, theme)
  const page = await ctx.newPage()
  const log = { pageErrors: [], consoleErrors: [], failed: [] }
  page.on('pageerror', (e) => log.pageErrors.push(e.message.slice(0, 200)))
  page.on('console', (m) => { if (m.type() === 'error') log.consoleErrors.push(m.text().slice(0, 100) + ' @ ' + (m.location().url || '').replace(BASE, '')) })
  page.on('response', (r) => { if (r.status() >= 400) log.failed.push(`${r.status()} ${new URL(r.url()).pathname}`) })
  if (clock) await page.clock.install()
  const s = { ctx, page, log }; sessions.push(s); return s
}
const toastText = async (p) => (await p.locator('[role=status]').allInnerTexts()).join(' | ')
const overflow = (p) => p.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1)
const ls = (p, k) => p.evaluate((key) => localStorage.getItem(key), k)

try {
  console.log('\n══ A. Register page: no Manager, password rule, tamper-proof role ══')
  const A = await session()
  await A.page.goto(`${BASE}/register`, { waitUntil: 'networkidle' })
  const txt = await A.page.evaluate(() => document.body.innerText)
  const opts = await A.page.locator('select option').allInnerTexts()
  check('A1 the Manager card and the Manager option are gone; Tenant and Owner remain', !/Manager|Property Manager/.test(txt) && opts.join('|') === 'Tenant|Property Owner', `${opts.join('|')}`)
  check('A2 password hint says at least 8 characters and mentions the emailed code', /At least 8 characters/.test(txt) && /email you a code/.test(txt))
  await A.page.fill('input[placeholder="Amit Kumar"]', 'Ui Owner'); await A.page.fill('input[type=email]', EM.owner)
  await A.page.locator('select').selectOption('owner')
  await A.page.locator('input[minlength="8"], input[placeholder="Min 8 characters"]').first().fill('short1')
  await A.page.getByRole('button', { name: /Create Account/ }).click(); await A.page.waitForTimeout(400)
  check('A3 a 6-character password is stopped in the form (no request made, still on /register)', A.page.url().endsWith('/register') && pg(`select count(*) from users where email='${EM.owner}'`) === '0')
  // tamper: rewrite the outgoing request so it asks for a manager account
  await A.page.route('**/auth/register', async (route) => { const b = JSON.parse(route.request().postData()); b.role = 'manager'; await route.continue({ postData: JSON.stringify(b) }) })
  await A.page.locator('input[placeholder="Min 8 characters"]').fill(PW)
  await A.page.getByRole('button', { name: /Create Account/ }).click(); await A.page.waitForTimeout(900)
  check('A4 a browser-tampered request for role=manager is refused by the server (message shown, no account, no OTP page)', /can't be created through sign-up/.test(await toastText(A.page)) && pg(`select count(*) from users where email='${EM.owner}'`) === '0' && A.page.url().endsWith('/register'), (await toastText(A.page)).slice(0, 90))
  await A.page.unroute('**/auth/register')
  await A.page.screenshot({ path: `${OUT}/register.png`, fullPage: true })

  console.log('\n══ B. Owner sign-up -> OTP screen -> verified -> signed in ══')
  await A.page.getByRole('button', { name: /Create Account/ }).click()
  await A.page.waitForURL('**/verify-email', { timeout: 15000 })
  check('B1 sign-up ends on /verify-email showing the address; NO session was started', /authui_owner@example.com/.test(await A.page.getByTestId('verify-intro').innerText()) && (await ls(A.page, 'token')) === null && (await ls(A.page, 'refresh_token')) === null)
  check('B2 the account exists but is unverified (owner role)', pg(`select (not email_verified)::text||'|'||role from users where email='${EM.owner}'`) === 'true|OWNER')
  check('B3 the resend button is disabled with a countdown', (await A.page.getByTestId('resend').isDisabled()) && /Resend code in \d+s/.test(await A.page.getByTestId('resend').innerText()), await A.page.getByTestId('resend').innerText())
  await A.page.screenshot({ path: `${OUT}/verify.png`, fullPage: true })
  await A.page.getByTestId('otp-input').fill('12'); await A.page.getByTestId('verify-submit').click()
  check('B4 a short code is stopped in the form', /Enter the 6-digit code/.test(await A.page.getByTestId('otp-error').innerText()))
  const code = otpFor(EM.owner)
  const wrong = code === '000000' ? '111111' : '000000'
  await A.page.getByTestId('otp-input').fill(wrong); await A.page.getByTestId('verify-submit').click()
  await A.page.getByText(/attempts? left/).waitFor({ timeout: 8000 })
  check('B5 a wrong code shows the server message with attempts left; field cleared; still unverified', /4 attempts left/.test(await A.page.getByTestId('otp-error').innerText()) && (await A.page.getByTestId('otp-input').inputValue()) === '' && (await ls(A.page, 'token')) === null)
  await A.page.getByTestId('otp-input').fill('12ab34'); check('B6 the code field only accepts digits', (await A.page.getByTestId('otp-input').inputValue()) === '1234')
  await A.page.getByTestId('otp-input').fill(code)
  await A.page.getByTestId('verify-submit').click()
  await A.page.waitForURL('**/owner', { timeout: 15000 })
  await A.page.waitForLoadState('networkidle')
  check('B7 the correct code verifies the account and lands on the Owner dashboard', A.page.url().endsWith('/owner') && /Ui Owner/.test(await A.page.evaluate(() => document.body.innerText)))
  check('B8 the session holds an access token AND a refresh token; account verified in the DB', !!(await ls(A.page, 'token')) && !!(await ls(A.page, 'refresh_token')) && pg(`select email_verified from users where email='${EM.owner}'`) === 't')
  const firstRefresh = await ls(A.page, 'refresh_token')

  console.log('\n══ C. Unverified account signing in is sent to the OTP screen ══')
  const pend = await j('/auth/register', { method: 'POST', body: JSON.stringify({ email: EM.pending, full_name: 'Ui Pending', password: PW, role: 'tenant' }) })
  check('C0 setup: pending tenant registered via API', pend.status === 201)
  const C = await session()
  await C.page.goto(`${BASE}/login`, { waitUntil: 'networkidle' })
  await C.page.fill('input[type=email]', EM.pending); await C.page.fill('input[type=password]', PW)
  await C.page.locator('button[type=submit]').click()
  await C.page.waitForURL('**/verify-email', { timeout: 15000 })
  check('C1 correct password but unverified -> OTP screen with the server notice; no session', /verify your email/i.test(await C.page.getByTestId('otp-error').innerText()) && (await ls(C.page, 'token')) === null)
  await C.page.waitForTimeout(600)
  const c2 = otpFor(EM.pending)
  await C.page.getByTestId('otp-input').fill(c2); await C.page.getByTestId('verify-submit').click()
  await C.page.waitForURL('**/tenant', { timeout: 15000 })
  check('C2 entering the code signs the tenant in', C.page.url().endsWith('/tenant'))

  console.log('\n══ D. Resend countdown (fake clock) ══')
  const Dq = await j('/auth/register', { method: 'POST', body: JSON.stringify({ email: EM.thrott, full_name: 'Ui Throttle', password: PW, role: 'tenant' }) })
  const D = await session({ clock: true })
  await D.page.goto(`${BASE}/login`, { waitUntil: 'networkidle' })
  await D.page.fill('input[type=email]', EM.thrott); await D.page.fill('input[type=password]', PW)
  rd('del', `otp_cd:${EM.thrott}`)
  await D.page.locator('button[type=submit]').click()
  await D.page.waitForURL('**/verify-email', { timeout: 15000 })
  await D.page.clock.runFor(30000)
  check('D1 after 30 s the button still counts down (~30s)', /Resend code in (2\d|30)s/.test(await D.page.getByTestId('resend').innerText()), await D.page.getByTestId('resend').innerText())
  await D.page.clock.runFor(31000)
  check('D2 after 60 s "Resend code" is enabled', !(await D.page.getByTestId('resend').isDisabled()) && (await D.page.getByTestId('resend').innerText()) === 'Resend code')
  rd('del', `otp_cd:${EM.thrott}`)
  await D.page.getByTestId('resend').click(); await D.page.waitForTimeout(700)
  check('D3 clicking it asks the server for a new code and restarts the countdown', /Resend code in \d+s/.test(await D.page.getByTestId('resend').innerText()) && /new code is on its way/.test(await toastText(D.page)))
  rd('del', `otp_cd:${EM.thrott}`, `otp_sent:${EM.thrott}`)

  console.log('\n══ E. Login throttling in the real form ══')
  await j('/auth/users', { method: 'POST', body: JSON.stringify({ email: EM.sess, full_name: 'Ui Session', password: PW, role: 'tenant' }) }, (await j('/auth/login', { method: 'POST', body: JSON.stringify({ email: 'rajesh@propai.in', password: 'PropAI@2024' }) })).body.access_token)
  const E = await session()
  await E.page.goto(`${BASE}/login`, { waitUntil: 'networkidle' })
  rd('del', ...rd('keys', `login_fail:${EM.sess}:*`).split('\n').filter(Boolean).concat(['x']))
  const attempt = async (pw) => {
    await E.page.fill('input[type=email]', EM.sess); await E.page.fill('input[type=password]', pw)
    const [resp] = await Promise.all([E.page.waitForResponse((r) => r.url().includes('/auth/login')), E.page.locator('button[type=submit]').click()])
    await E.page.waitForTimeout(250)
    return resp.status()
  }
  const statuses = []
  for (let i = 0; i < 5; i++) statuses.push(await attempt(`wrong-${i}-password`))
  const t5 = await toastText(E.page)
  check('E1 five wrong passwords: 401 each, still "Invalid email or password", page stays on /login (the message is no longer lost to a reload)', statuses.join() === '401,401,401,401,401' && /Invalid email or password/.test(t5) && E.page.url().endsWith('/login'), statuses.join())
  const s6 = await attempt('wrong-6-password')
  const t6 = await toastText(E.page)
  check('E2 the 6th attempt: HTTP 429 and the toast reads "Too many failed sign-in attempts. Try again in N seconds."', s6 === 429 && /Too many failed sign-in attempts\. Try again in \d+ seconds/.test(t6), `${s6} ${t6.slice(0, 100)}`)
  const s7 = await attempt(PW)
  check('E3 even the correct password is refused while locked (429), no session, still /login', s7 === 429 && E.page.url().endsWith('/login') && (await ls(E.page, 'token')) === null, s7)
  await E.page.screenshot({ path: `${OUT}/throttled.png` })
  rd('del', ...rd('keys', `login_fail:${EM.sess}:*`).split('\n').filter(Boolean))
  await E.page.locator('button[type=submit]').click()
  await E.page.waitForURL('**/tenant', { timeout: 15000 })
  check('E4 after the window the right password signs in', E.page.url().endsWith('/tenant'))

  console.log('\n══ F. Short-lived token: silent refresh, rotation, revocation ══')
  const uid = pg(`select id from users where email='${EM.sess}'`)
  const oldRefresh = await ls(E.page, 'refresh_token')
  await E.page.evaluate((t) => localStorage.setItem('token', t), expiredJwt(uid, 'tenant'))
  const reqs = []; E.page.on('request', (r) => { if (r.url().includes('/auth/refresh')) reqs.push(r.method()) })
  await E.page.reload({ waitUntil: 'networkidle' }); await E.page.waitForTimeout(600)
  check('F1 reloading with an EXPIRED access token keeps the person signed in (no redirect to /login)', new URL(E.page.url()).pathname === '/tenant' && /Ui Session/.test(await E.page.evaluate(() => document.body.innerText)), E.page.url())
  const newRefresh = await ls(E.page, 'refresh_token'), newAccess = await ls(E.page, 'token')
  check('F2 exactly one refresh call happened, and BOTH tokens were replaced (rotation)', reqs.length === 1 && newRefresh !== oldRefresh && newAccess !== expiredJwt(uid, 'tenant'), `${reqs.length} calls`)
  const rep = await j('/auth/refresh', { method: 'POST', body: JSON.stringify({ refresh_token: oldRefresh }) })
  check('F3 the previous refresh token is dead server-side (401)', rep.status === 401)
  const after = await j('/auth/refresh', { method: 'POST', body: JSON.stringify({ refresh_token: newRefresh }) })
  check('F4 ...and replaying it revoked the session family (the newest token too)', after.status === 401)
  // the browser still holds the (now revoked) newest refresh token: an expired access token must now end the session cleanly
  await E.page.evaluate((t) => localStorage.setItem('token', t), expiredJwt(uid, 'tenant'))
  await E.page.reload({ waitUntil: 'networkidle' }); await E.page.waitForTimeout(800)
  check('F5 expired access token + revoked refresh token -> back to /login with the session cleared', new URL(E.page.url()).pathname === '/login' && (await ls(E.page, 'token')) === null && (await ls(E.page, 'refresh_token')) === null, E.page.url())

  console.log('\n══ G. Mid-session expiry and sign out ══')
  const G = await session()
  await G.page.goto(`${BASE}/login`, { waitUntil: 'networkidle' })
  await G.page.fill('input[type=email]', EM.sess); await G.page.fill('input[type=password]', PW); await G.page.locator('button[type=submit]').click()
  await G.page.waitForURL('**/tenant', { timeout: 15000 })
  await G.page.evaluate((t) => localStorage.setItem('token', t), expiredJwt(uid, 'tenant'))
  await G.page.getByRole('link', { name: 'Payments' }).click()
  await G.page.getByRole('heading', { name: 'Payments', exact: true }).waitFor({ timeout: 15000 })
  await G.page.waitForTimeout(800)
  check('G1 the access token expires WHILE using the app: the next page still loads (silent refresh + retry), user stays on Payments', G.page.url().endsWith('/tenant/payments') && !(await G.page.getByText(/couldn't load/i).count()))
  const rtBefore = await ls(G.page, 'refresh_token')
  await G.page.getByText('Sign Out').click(); await G.page.waitForURL('**/login', { timeout: 10000 })
  check('G2 Sign Out clears both tokens', (await ls(G.page, 'token')) === null && (await ls(G.page, 'refresh_token')) === null)
  check('G3 ...and revokes the refresh token on the server (401 if replayed)', (await j('/auth/refresh', { method: 'POST', body: JSON.stringify({ refresh_token: rtBefore }) })).status === 401)

  console.log('\n══ H. Manager: Add user (the only way to make a manager) ══')
  const H = await session()
  await H.page.goto(`${BASE}/login`, { waitUntil: 'networkidle' })
  await H.page.getByText('rajesh@propai.in').click(); await H.page.locator('button[type=submit]').click()
  await H.page.waitForURL('**/manager', { timeout: 15000 })
  await H.page.getByRole('link', { name: 'Users & Roles' }).click()
  await H.page.getByTestId('add-user').waitFor({ timeout: 15000 })
  await H.page.getByTestId('add-user').click()
  await H.page.locator('#au-name').fill('Ui NewMgr'); await H.page.locator('#au-email').fill('bad-email'); await H.page.locator('#au-pass').fill('short')
  await H.page.getByTestId('create-user').click()
  check('H1 invalid email is stopped in the dialog', /valid email/.test(await H.page.getByTestId('add-user-error').innerText()))
  await H.page.locator('#au-email').fill(EM.mgr); await H.page.getByTestId('create-user').click()
  check('H2 a short password is stopped in the dialog', /at least 8/.test(await H.page.getByTestId('add-user-error').innerText()))
  await H.page.locator('#au-role').selectOption('manager')
  check('H3 choosing Manager shows a warning', (await H.page.getByTestId('manager-warning').count()) === 1)
  await H.page.locator('#au-pass').fill(PW)
  await H.page.screenshot({ path: `${OUT}/add-user.png` })
  await H.page.getByTestId('create-user').click()
  await H.page.getByTestId('create-user').waitFor({ state: 'detached', timeout: 15000 })
  await H.page.waitForTimeout(600)
  check('H4 the new manager is in the list, created verified', (await H.page.getByText(EM.mgr).count()) >= 1 && pg(`select role||'|'||email_verified::text from users where email='${EM.mgr}'`) === 'MANAGER|true')
  await H.page.getByTestId('add-user').click(); await H.page.locator('#au-name').fill('Ui NewMgr'); await H.page.locator('#au-email').fill(EM.mgr); await H.page.locator('#au-pass').fill(PW)
  await H.page.getByTestId('create-user').click(); await H.page.waitForTimeout(600)
  check('H5 a duplicate email shows the server error in the dialog', /already registered/.test(await H.page.getByTestId('add-user-error').innerText()))
  const N = await session()
  await N.page.goto(`${BASE}/login`, { waitUntil: 'networkidle' })
  await N.page.fill('input[type=email]', EM.mgr); await N.page.fill('input[type=password]', PW); await N.page.locator('button[type=submit]').click()
  await N.page.waitForURL('**/manager', { timeout: 15000 })
  check('H6 the newly created manager signs in and reaches the Manager dashboard', N.page.url().endsWith('/manager'))
  const T = await session()
  await T.page.goto(`${BASE}/login`, { waitUntil: 'networkidle' })
  await T.page.getByText('amit@example.in').click(); await T.page.locator('button[type=submit]').click()
  await T.page.waitForURL('**/tenant', { timeout: 15000 })
  await T.page.goto(`${BASE}/manager/users`, { waitUntil: 'networkidle' }); await T.page.waitForTimeout(500)
  check('H7 a tenant cannot reach Users & Roles (redirected home), so never sees Add user', new URL(T.page.url()).pathname === '/tenant' && (await T.page.getByTestId('add-user').count()) === 0)

  console.log('\n══ I. Look, themes, phones ══')
  for (const [sname, viewport] of [['desktop', { width: 1440, height: 900 }], ['mobile', { width: 390, height: 844 }], ['small', { width: 320, height: 640 }]]) {
    for (const theme of ['light', 'dark']) {
      const S = await session({ theme, viewport })
      await S.page.goto(`${BASE}/verify-email`, { waitUntil: 'networkidle' })
      const f = await S.page.evaluate(auditFn)
      const ovf = await overflow(S.page)
      const btn = await S.page.getByTestId('verify-submit').boundingBox()
      check(`I ${sname}/${theme} verify page: no overflow, button inside viewport, WCAG contrast clean`, !ovf && btn && btn.x >= 0 && btn.x + btn.width <= viewport.width && f.length === 0, f.length ? JSON.stringify(f.slice(0, 2)) : `ovf=${ovf}`)
      await S.page.goto(`${BASE}/register`, { waitUntil: 'networkidle' })
      const ovf2 = await overflow(S.page)
      const f2 = (await S.page.evaluate(auditFn)).filter((x) => !/^(Create your account|Choose your role|Major Project|At least 8 characters|Already have an account\?|Sign in|Join the PropAI platform|Property Owner|Tenant|Selected)/.test(x.text))
      check(`I ${sname}/${theme} register page: no overflow`, !ovf2, `contrast findings on register (pre-existing styles): ${f2.length}`)
      if (theme === 'light' && sname === 'mobile') await S.page.screenshot({ path: `${OUT}/register-mobile.png`, fullPage: true })
    }
  }

  const errs = sessions.flatMap((s) => [...s.log.pageErrors, ...s.log.consoleErrors]).filter((e) => !/favicon|status of (400|401|403|429)/.test(e))
  check('J no uncaught errors / unexpected console errors (deliberate 4xx from the flows and the known favicon excluded)', errs.length === 0, errs.slice(0, 3).join(' | '))
  const bad5xx = sessions.flatMap((s) => s.log.failed).filter((f) => /^5\d\d /.test(f))
  check('J no 5xx responses anywhere in the flows', bad5xx.length === 0, bad5xx.join(','))
} catch (err) {
  check('script completed without throwing', false, String(err.message).split('\n')[0])
} finally {
  for (const s of sessions) await s.ctx.close().catch(() => {})
  await browser.close()
  pg("delete from users where email like 'authui\\_%'")
  for (const pat of ['otp*authui*', 'login_fail:authui*', 'login_fail:*authui*']) { const ks = rd('--scan', '--pattern', pat).split('\n').filter(Boolean); if (ks.length) rd('del', ...ks) }
  check('CLEANUP: user count back to baseline', pg('select count(*) from users') === BASEU, `${BASEU} vs ${pg('select count(*) from users')}`)
  console.log(`\n${results.filter(Boolean).length}/${results.length} passed`)
  process.exit(results.every(Boolean) ? 0 : 1)
}
