import { chromium } from 'playwright-core'
import fs from 'node:fs'
import { execFileSync } from 'node:child_process'

const BASE = 'http://localhost:3000', API = 'http://localhost:8000'
const OUT = 'shots/dirs'; fs.mkdirSync(OUT, { recursive: true })
const src = fs.readFileSync('audit.mjs', 'utf8')
const auditFn = new Function('return ' + src.match(/const auditFn = (\(\) => \{[\s\S]*?\r?\n\})\r?\n\r?\nconst browser/)[1])()
const results = []
const check = (name, ok, detail = '') => { results.push(!!ok); console.log((ok ? 'PASS ' : 'FAIL ') + name + (detail !== '' ? `  [${String(detail).slice(0, 180)}]` : '')) }
const run = (cmd, args) => execFileSync(cmd, args, { encoding: 'utf8' }).trim()
const pg = (sql) => run('docker', ['exec', 'property_postgres', 'psql', '-U', 'postgres', '-d', 'property_management', '-Atc', sql])
const mongo = (js) => run('docker', ['exec', '-i', 'property_mongodb', 'mongosh', '-u', 'mongo', '-p', 'mongo123', '--authenticationDatabase', 'admin', '--quiet', '--eval', `const d=db.getSiblingDB("property_management"); ${js}`])
const login = async (email) => { const d = await (await fetch(`${API}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password: 'PropAI@2024' }) })).json(); return { tok: d.access_token, h: { Authorization: `Bearer ${d.access_token}`, 'Content-Type': 'application/json' } } }
const T0 = new Date().toISOString()

const browser = await chromium.launch({ executablePath: process.env.BROWSER_PATH || 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe', headless: true })
const sessions = []
async function session(theme = 'light', tok = null, viewport = { width: 1440, height: 1500 }) {
  const ctx = await browser.newContext({ viewport, colorScheme: theme })
  await ctx.addInitScript(([t, k]) => { if (k) localStorage.setItem('token', k); if (!sessionStorage.getItem('seeded')) { localStorage.setItem('propai-theme', t); sessionStorage.setItem('seeded', '1') } }, [theme, tok])
  await ctx.route(/^https:\/\/wa\.me\//, (r) => r.fulfill({ status: 200, contentType: 'text/html', body: '<title>stub</title>stub' }))
  const page = await ctx.newPage()
  const log = { pageErrors: [], consoleErrors: [], requests: [] }
  page.on('pageerror', (e) => log.pageErrors.push(e.message.slice(0, 200)))
  page.on('console', (m) => { if (m.type() === 'error') log.consoleErrors.push(m.text().slice(0, 200)) })
  ctx.on('request', (r) => log.requests.push(r.url()))
  const s = { ctx, page, log }; sessions.push(s); return s
}
const shot = (p, n) => p.screenshot({ path: `${OUT}/${n}.png` })
const contrast = async (p, label) => { const f = await p.evaluate(auditFn); check(`contrast (0 failures): ${label}`, f.length === 0, f.length ? JSON.stringify(f.slice(0, 3)) : '') }
const setTheme = async (p, t) => { await p.evaluate((v) => localStorage.setItem('propai-theme', v), t); await p.reload({ waitUntil: 'networkidle' }); await p.waitForTimeout(400) }
const cards = (p) => p.getByTestId('service-providers').getByTestId('provider-card')
const openProviders = async (p) => { await p.getByTestId('section-providers').click(); await cards(p).first().waitFor({ timeout: 10000 }) }
const names = (p) => cards(p).getByTestId('provider-name').allInnerTexts()
const card = (p, name) => cards(p).filter({ has: p.getByTestId('provider-name').filter({ hasText: new RegExp(`^${name}$`) }) })

const vikram = await login('vikram@propai.in'), amit = await login('amit@example.in')
const madeRequests = []
let renamed = null
try {
  console.log('\n══ A. Owner login -> Maintenance -> Service Providers ══')
  const O = await session('light')
  await O.page.goto(`${BASE}/login`, { waitUntil: 'networkidle' })
  await O.page.fill('input[type=email]', 'vikram@propai.in'); await O.page.fill('input[type=password]', 'PropAI@2024')
  await O.page.locator('button[type=submit]').click()
  await O.page.getByRole('heading', { name: 'Owner Dashboard' }).waitFor({ timeout: 10000 })
  await O.page.getByRole('link', { name: 'Maintenance' }).click(); await O.page.getByTestId('record-row').first().waitFor({ timeout: 10000 })
  check('A1 Maintenance opens on the requests as before, with a "Service providers" section tab', (await O.page.getByTestId('section-requests').getAttribute('aria-selected')) === 'true' && (await O.page.getByTestId('section-providers').isVisible()))
  await openProviders(O.page)
  const apiList = (await (await fetch(`${API}/service-providers/`, { headers: vikram.h })).json()).providers
  const shown = await names(O.page)
  check('A2 the section lists the 17 providers from the backend', shown.length === 17 && new Set(shown).size === 17 && apiList.every((p) => shown.includes(p.name)), shown.length)
  await shot(O.page, 'A-providers-light'); await contrast(O.page, 'Service providers (light)')

  console.log('\n══ B. Provider card (your layout) ══')
  const rajesh = card(O.page, 'Rajesh Plumbing Services')
  const t = async (id) => (await rajesh.getByTestId(id).innerText()).trim()
  check('B1 name, category, status', (await t('provider-name')) === 'Rajesh Plumbing Services' && (await t('provider-category')) === 'Plumber' && (await t('provider-status')) === 'Available')
  check('B2 problem types: Tap leakage • Pipe blockage • Water leakage', (await t('provider-problems')).includes('Tap leakage • Pipe blockage • Water leakage'), await t('provider-problems'))
  check('B3 availability 9:00 AM – 7:00 PM, visit charge ₹500, service area', (await t('provider-availability')) === '9:00 AM – 7:00 PM' && (await t('provider-charge')) === '₹500' && (await t('provider-area')).includes('Mumbai / Navi Mumbai'))
  check('B4 phone shown as a clearly fake placeholder (+91 00000 00001)', (await t('provider-phone')) === '+91 00000 00001')
  check('B5 marked Demo, with a note that the number is fake', (await t('provider-demo')) === 'Demo' && /fake placeholder/.test(await t('demo-note')))
  check('B6 CALL uses a proper tel: link', (await rajesh.getByTestId('provider-call').getAttribute('href')) === 'tel:+910000000001')
  const wa = await rajesh.getByTestId('provider-whatsapp').getAttribute('href')
  check('B7 WHATSAPP uses a proper wa.me link with the number (opens in a new tab)', wa === 'https://wa.me/910000000001' && (await rajesh.getByTestId('provider-whatsapp').getAttribute('target')) === '_blank' && /noopener/.test(await rajesh.getByTestId('provider-whatsapp').getAttribute('rel')), wa)
  const [waPage] = await Promise.all([O.ctx.waitForEvent('page'), rajesh.getByTestId('provider-whatsapp').click()])
  check('B8 clicking WhatsApp opens WhatsApp in a NEW tab; PropAI stays open (nothing is sent by us)', waPage.url().startsWith('https://wa.me/910000000001') && (await O.page.getByTestId('service-providers').isVisible())); await waPage.close()
  check('B9 demo providers have no Edit / Remove buttons', (await rajesh.getByTestId('edit-provider').count()) === 0 && (await rajesh.getByTestId('remove-provider').count()) === 0)
  check('B10 no ratings shown (no rating system exists)', !/rating|stars?\b/i.test(await O.page.getByTestId('service-providers').innerText()))

  console.log('\n══ C. Filtering ══')
  const chips = await O.page.locator('[data-testid^=cat-]').allInnerTexts()
  check('C1 filter chips in your order: All, Plumber, Electrician, Carpenter, AC, Cleaning, Locksmith (+ Handyman), with counts', chips.map((c) => c.replace(/\s+/g, ' ').trim()).join('|') === 'All (17)|Plumber (4)|Electrician (3)|Carpenter (2)|AC (2)|Cleaning (2)|Locksmith (2)|Handyman (2)', chips.join('|'))
  for (const [key, n, first] of [['plumber', 4, 'Plumber'], ['electrician', 3, 'Electrician'], ['carpenter', 2, 'Carpenter'], ['ac_technician', 2, 'AC Technician'], ['cleaning', 2, 'Cleaning Service'], ['locksmith', 2, 'Locksmith'], ['handyman', 2, 'General Handyman']]) {
    await O.page.getByTestId(`cat-${key}`).click()
    const cats = await cards(O.page).getByTestId('provider-category').allInnerTexts()
    check(`C2 filter ${first}: ${n} providers, all "${first}"`, cats.length === n && cats.every((c) => c === first), cats.length)
  }
  await O.page.getByTestId('cat-plumber').click(); await O.page.getByTestId('only-available').check()
  check('C3 "Available only" hides the unavailable plumber (4 -> 3)', (await cards(O.page).count()) === 3 && !(await names(O.page)).includes('Namma Bengaluru Plumbers'))
  await O.page.getByTestId('only-available').uncheck()
  check('C3 …and the unavailable one is labelled Unavailable', (await card(O.page, 'Namma Bengaluru Plumbers').getByTestId('provider-status').innerText()) === 'Unavailable')
  await O.page.getByTestId('cat-all').click(); await O.page.getByLabel('Search service providers').fill('geyser')
  check('C4 search finds by problem/description ("geyser" -> XYZ Plumbing)', JSON.stringify(await names(O.page)) === JSON.stringify(['XYZ Plumbing']))
  await O.page.getByLabel('Search service providers').fill('zzzz')
  await O.page.getByText('No providers match').waitFor()
  check('C5 no match -> friendly message + Clear filters', await O.page.getByRole('button', { name: 'Clear filters' }).isVisible())
  await O.page.getByRole('button', { name: 'Clear filters' }).click(); check('C5 …clearing restores all 17', (await cards(O.page).count()) === 17)

  console.log('\n══ D. Data comes from the backend/database, not the React code ══')
  const bundle = run('docker', ['exec', 'property_frontend', 'sh', '-c', "grep -rlE 'Rajesh Plumbing|ABC Electrical|Sparkle Home|SafeKey' /usr/share/nginx/html | wc -l"])
  check('D1 the built frontend contains none of the provider names', bundle === '0', bundle)
  const srcHits = run('docker', ['exec', 'property_backend', 'sh', '-c', "grep -rlE 'Rajesh Plumbing' /app/app | wc -l"])
  check('D2 provider names live only in the seeder (backend/seed_service_providers.py), not in the API code', srcHits === '0', srcHits)
  renamed = pg("update service_providers set name='Rajesh Plumbing Services (edited in DB)' where name='Rajesh Plumbing Services' returning id")
  await O.page.reload({ waitUntil: 'networkidle' }); await openProviders(O.page)
  check('D3 change a row in the DATABASE -> the page shows it after reload (data is live from the backend)', (await names(O.page)).includes('Rajesh Plumbing Services (edited in DB)') && !(await names(O.page)).includes('Rajesh Plumbing Services'))
  pg("update service_providers set name='Rajesh Plumbing Services' where name='Rajesh Plumbing Services (edited in DB)'"); renamed = null
  check('D3 …and it is restored', pg("select count(*) from service_providers where name='Rajesh Plumbing Services'") === '1')
  const reqs = O.log.requests.filter((u) => u.includes('/service-providers/'))
  check('D4 the browser loaded the providers from GET /service-providers/', reqs.length > 0)

  console.log('\n══ E. Add / edit / remove a provider ══')
  await O.page.getByTestId('add-provider').click()
  const dlg = O.page.getByRole('dialog', { name: 'Add a service provider' }); await dlg.waitFor()
  await dlg.getByTestId('save-provider').click()
  check('E1 empty form: messages for name, phone and area; nothing saved', (await dlg.locator('[role=alert]').count()) >= 3 && pg("select count(*) from service_providers where not is_demo") === '0')
  await dlg.locator('#pf-name').fill('TEST Ravi Plumbing'); await dlg.locator('#pf-phone').fill('12345'); await dlg.locator('#pf-area').fill('Mumbai / Thane'); await dlg.getByTestId('save-provider').click()
  check('E2 invalid phone rejected', (await dlg.getByText(/valid phone number/).count()) === 1)
  await shot(O.page, 'E-form-errors-light'); await contrast(O.page, 'Add provider form with errors (light)')
  await dlg.locator('#pf-phone').fill('98765 43210'); await dlg.getByTestId('same-as-phone').check()
  await dlg.locator('#pf-hours').fill('8:00 AM – 6:00 PM'); await dlg.locator('#pf-charge').fill('350'); await dlg.locator('#pf-problems').fill('Tap leakage, Drain clearing'); await dlg.locator('#pf-desc').fill('Leaks and drains.')
  await dlg.getByTestId('save-provider').click()
  await card(O.page, 'TEST Ravi Plumbing').waitFor()
  const mine = card(O.page, 'TEST Ravi Plumbing')
  check('E3 saved: appears with the details, phone formatted, NOT marked Demo, editable', (await mine.getByTestId('provider-phone').innerText()) === '+91 98765 43210' && (await mine.getByTestId('provider-charge').innerText()) === '₹350' && (await mine.getByTestId('provider-demo').count()) === 0 && (await mine.getByTestId('edit-provider').count()) === 1)
  check('E3 …stored for this owner in the database (owner 2, E.164 phone + WhatsApp same as phone)', pg("select created_by||'|'||phone||'|'||whatsapp from service_providers where name='TEST Ravi Plumbing'") === '2|+919876543210|+919876543210')
  check('E3 …its Call/WhatsApp links use the real number', (await mine.getByTestId('provider-call').getAttribute('href')) === 'tel:+919876543210' && (await mine.getByTestId('provider-whatsapp').getAttribute('href')) === 'https://wa.me/919876543210')
  await mine.getByTestId('edit-provider').click()
  const ed = O.page.getByRole('dialog', { name: 'Edit service provider' }); await ed.waitFor()
  check('E4 edit form is pre-filled', (await ed.locator('#pf-name').inputValue()) === 'TEST Ravi Plumbing' && (await ed.locator('#pf-charge').inputValue()) === '350' && (await ed.getByTestId('same-as-phone').isChecked()))
  await ed.locator('#pf-status').selectOption('unavailable'); await ed.getByTestId('save-provider').click()
  await ed.waitFor({ state: 'detached' })
  check('E5 edit saved: now Unavailable', (await card(O.page, 'TEST Ravi Plumbing').getByTestId('provider-status').innerText()) === 'Unavailable')
  await card(O.page, 'TEST Ravi Plumbing').getByTestId('remove-provider').click()
  check('E6 remove asks first (nothing deleted yet)', (await O.page.getByTestId('confirm-remove-box').isVisible()) && pg("select count(*) from service_providers where name='TEST Ravi Plumbing'") === '1')
  await O.page.getByTestId('confirm-remove').click(); await card(O.page, 'TEST Ravi Plumbing').waitFor({ state: 'detached' })
  check('E6 removed from the page and the database', pg("select count(*) from service_providers where name='TEST Ravi Plumbing'") === '0' && (await cards(O.page).count()) === 17)

  console.log('\n══ F. From a maintenance request ══')
  const mk = async (title, description, category) => { const r = await (await fetch(`${API}/maintenance/`, { method: 'POST', headers: amit.h, body: JSON.stringify({ title, description, urgency: 'medium', category }) })).json(); madeRequests.push(r.id); return r.id }
  await mk('Bathroom tap is leaking', 'Water is continuously leaking from the bathroom tap.', 'plumbing'); await mk('Fan is not working', 'Bedroom ceiling fan', 'other')
  await O.page.reload({ waitUntil: 'networkidle' }); await O.page.getByTestId('record-row').first().waitFor()
  await O.page.getByLabel('Search maintenance records').fill('Bathroom tap is leaking'); await O.page.waitForTimeout(250)
  await O.page.getByTestId('record-row').first().getByRole('button', { name: /View details/ }).click()
  const details = O.page.getByRole('dialog'); await details.waitFor()
  check('F1 request details have a "Contact Service Provider" action', (await details.getByTestId('contact-provider').innerText()).includes('Contact Service Provider'))
  check('F2 providers are not loaded until the owner asks', (await details.getByTestId('request-providers').count()) === 0)
  await details.getByTestId('contact-provider').click(); const panel = details.getByTestId('request-providers'); await panel.getByTestId('flow-category').waitFor()
  check('F3 flow: Problem type "Plumbing" -> Recommended service "Plumber" (from the request\'s own category)', (await panel.getByTestId('flow-problem').innerText()) === 'Plumbing' && (await panel.getByTestId('flow-category').innerText()) === 'Plumber' && /request's category/.test(await panel.innerText()))
  check('F4 Available providers: 3 (+1 unavailable), the Mumbai ones first and flagged for the property\'s city', (await panel.getByTestId('flow-count').innerText()) === '3 (+1 unavailable)' && JSON.stringify(await panel.getByTestId('provider-name').allInnerTexts()) === JSON.stringify(['Rajesh Plumbing Services', 'XYZ Plumbing', 'Pune Pipe & Drain Works']) && (await panel.getByTestId('provider-area-match').count()) === 2)
  const pc = panel.getByTestId('provider-card').first()
  check('F5 each shows phone, WhatsApp button, availability and visit charge (service fee)', (await pc.getByTestId('provider-phone').innerText()) === '+91 00000 00001' && (await pc.getByTestId('provider-call').getAttribute('href')) === 'tel:+910000000001' && (await pc.getByTestId('provider-charge').innerText()) === '₹500' && (await pc.getByTestId('provider-availability').innerText()) === '9:00 AM – 7:00 PM')
  const waMsg = decodeURIComponent((await pc.getByTestId('provider-whatsapp').getAttribute('href')).split('?text=')[1] || '')
  check('F6 WhatsApp opens with a pre-filled message about THIS request (owner can edit it; nothing sent by us)', /Bathroom tap is leaking/.test(waMsg) && (await pc.getByTestId('provider-whatsapp').getAttribute('href')).startsWith('https://wa.me/910000000001?text='), waMsg.slice(0, 100))
  await shot(O.page, 'F-request-panel-light'); await contrast(O.page, 'Request details with providers (light)')
  await details.getByTestId('view-all-providers').click()
  await O.page.getByTestId('service-providers').waitFor(); await cards(O.page).first().waitFor()
  check('F7 "View all Plumber providers" -> Service providers section, Plumber filter on, 4 providers', (await O.page.getByTestId('cat-plumber').getAttribute('aria-pressed')) === 'true' && (await cards(O.page).count()) === 4 && (await O.page.getByTestId('section-providers').getAttribute('aria-selected')) === 'true')
  await O.page.getByTestId('section-requests').click(); await O.page.getByLabel('Search maintenance records').fill('Fan is not working'); await O.page.waitForTimeout(250)
  await O.page.getByTestId('record-row').first().getByRole('button', { name: /View details/ }).click()
  await O.page.getByRole('dialog').getByTestId('contact-provider').click(); await O.page.getByRole('dialog').getByTestId('flow-category').waitFor()
  check('F8 "Fan is not working" (category Other) -> Electrician, decided from the wording', (await O.page.getByRole('dialog').getByTestId('flow-category').innerText()) === 'Electrician' && /wording/.test(await O.page.getByRole('dialog').getByTestId('request-providers').innerText()) && (await O.page.getByRole('dialog').getByTestId('provider-name').allInnerTexts())[0] === 'ABC Electrical Services')
  await O.page.keyboard.press('Escape')
  const resolved = (await (await fetch(`${API}/maintenance/`, { headers: vikram.h })).json()).find((r) => r.status === 'resolved')
  if (resolved) {
    await O.page.getByLabel('Search maintenance records').fill(resolved.title); await O.page.waitForTimeout(250)
    await O.page.getByTestId('record-row').first().getByRole('button', { name: /View details/ }).click()
    check('F9 resolved requests offer no "Contact Service Provider"', (await O.page.getByRole('dialog').getByTestId('contact-provider').count()) === 0); await O.page.keyboard.press('Escape')
  }

  console.log('\n══ G. Phone, tablet, dark mode ══')
  const M = await session('light', vikram.tok, { width: 400, height: 900 })
  await M.page.goto(`${BASE}/owner/maintenance`, { waitUntil: 'networkidle' }); await M.page.getByTestId('record-row').first().waitFor().catch(() => {}); await openProviders(M.page)
  const ov = await M.page.evaluate(() => ({ page: (window.scrollTo(500, 0), window.scrollX) }))
  const geo = await cards(M.page).first().locator('a').evaluateAll((els) => els.map((e) => { const r = e.getBoundingClientRect(); return { h: r.height, right: r.right } }))
  check('G1 400 px: no sideways scrolling, cards in one column, Call/WhatsApp >= 40 px tall and on screen', ov.page === 0 && geo.every((g) => g.h >= 39 && g.right <= 400) && (await cards(M.page).evaluateAll((els) => new Set(els.map((e) => Math.round(e.getBoundingClientRect().left))).size)) === 1, JSON.stringify({ ov, geo }))
  await shot(M.page, 'G-phone'); await contrast(M.page, 'Service providers at phone width')
  const Tb = await session('light', vikram.tok, { width: 820, height: 1100 })
  await Tb.page.goto(`${BASE}/owner/maintenance`, { waitUntil: 'networkidle' }); await openProviders(Tb.page)
  check('G2 tablet: two columns, nothing overflows', (await cards(Tb.page).evaluateAll((els) => new Set(els.map((e) => Math.round(e.getBoundingClientRect().left))).size)) === 2 && (await Tb.page.evaluate(() => (window.scrollTo(500, 0), window.scrollX))) === 0)
  await setTheme(O.page, 'dark'); await openProviders(O.page)
  await shot(O.page, 'G-dark'); await contrast(O.page, 'Service providers (dark)')
  await O.page.getByTestId('add-provider').click(); await O.page.getByRole('dialog').getByTestId('save-provider').click(); await shot(O.page, 'G-form-dark'); await contrast(O.page, 'Add provider form with errors (dark)')
  await O.page.keyboard.press('Escape')
  await O.page.getByTestId('section-requests').click(); await O.page.getByLabel('Search maintenance records').fill('Bathroom tap is leaking'); await O.page.waitForTimeout(250)
  await O.page.getByTestId('record-row').first().getByRole('button', { name: /View details/ }).click(); await O.page.getByRole('dialog').getByTestId('contact-provider').click(); await O.page.getByRole('dialog').getByTestId('flow-category').waitFor()
  await shot(O.page, 'G-panel-dark'); await contrast(O.page, 'Request details with providers (dark)')
  await O.page.keyboard.press('Escape')

  console.log('\n══ H. Other roles + console ══')
  const T = await session('light', amit.tok)
  await T.page.goto(`${BASE}/tenant/maintenance`, { waitUntil: 'networkidle' }); await T.page.getByTestId('request-card').first().waitFor()
  check('H1 tenant Maintenance page unchanged: no provider features', !/Service provider|Contact Service|repair contact/i.test(await T.page.locator('body').innerText()) && (await T.page.getByTestId('request-card').count()) >= 5)
  const M2 = await session('light', (await login('rajesh@propai.in')).tok)
  await M2.page.goto(`${BASE}/manager`, { waitUntil: 'networkidle' }); await M2.page.waitForTimeout(700)
  check('H2 manager dashboard still renders', (await M2.page.locator('#root').innerText()).includes('Manager Dashboard'))
  const uncaught = sessions.flatMap((s) => s.log.pageErrors)
  const unexpected = sessions.flatMap((s) => s.log.consoleErrors).filter((m) => !/status of (4\d\d|5\d\d)|net::ERR_FAILED|Failed to load resource/.test(m))
  check('H3 no JavaScript errors or unexpected console errors', uncaught.length === 0 && unexpected.length === 0, JSON.stringify([...uncaught, ...new Set(unexpected)]))
} finally {
  console.log('\n══ Cleanup ══')
  if (renamed) pg("update service_providers set name='Rajesh Plumbing Services' where name like 'Rajesh Plumbing Services (edited%'")
  pg("delete from service_providers where name like 'TEST %'")
  for (const id of madeRequests) mongo(`d.maintenance_requests.deleteOne({_id:ObjectId("${id}")})`)
  const n = mongo(`print(d.notifications.deleteMany({created_at:{$gte:"${T0}"}}).deletedCount)`)
  console.log(`   ${madeRequests.length} test requests removed, ${n} test notifications removed; providers now ${pg('select count(*) from service_providers')}`)
  for (const s of sessions) await s.ctx.close().catch(() => {})
  await browser.close()
}
console.log(`\n${results.filter(Boolean).length}/${results.length} UI checks passed`)
process.exit(results.every(Boolean) ? 0 : 1)
